C_SOURCES = $(wildcard kernel/*.c drivers/*.c cpu/*.c libc/*.c)
HEADERS = $(wildcard kernel/*.h drivers/*.h cpu/*.h libc/*.h)
OBJ = ${C_SOURCES:.c=.o} cpu/interrupt.o

CC = gcc
GDB = gdb
CFLAGS = -g -m32 -ffreestanding -fno-pie -Wall -Wextra -Werror

os-image.bin: boot/boot.bin kernel.bin
    cat $^ > os-image.bin

kernel.bin: kernel/entry.o ${OBJ}
    ld -m elf_i386 -o $@ -Ttext 0x1000 $^ --oformat binary

kernel.elf: kernel/entry.o ${OBJ}
    ld -m elf_i386 -o $@ -Ttext 0x1000 $^

run: os-image.bin
    qemu-system-i386 -fda os-image.bin

debug: os-image.bin kernel.elf
    qemu-system-i386 -s -fda os-image.bin &
    ${GDB} -ex "target remote localhost:1234" -ex "symbol-file kernel.elf"

%.o: %.c ${HEADERS}
    ${CC} ${CFLAGS} -c $< -o $@

%.o: %.asm
    nasm $< -f elf -o $@

%.bin: %.asm
    nasm $< -f bin -o $@

clean:
    rm -rf *.bin *.dis *.o os-image.bin *.elf
    rm -rf kernel/*.o boot/*.bin drivers/*.o cpu/*.o libc/*.o

.PHONY: clean run debug
